"""Add unique constraint to execution logs

Revision ID: 957cd111d089
Revises: 685d28916ea4
Create Date: 2026-01-09 15:02:41.539363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957cd111d089'
down_revision: Union[str, Sequence[str], None] = '685d28916ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_execution_logs_event_workflow', 'execution_logs', ['event_id', 'workflow_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_execution_logs_event_workflow', 'execution_logs', type_='unique')
    # ### end Alembic commands ###
