"""Add attempts dlq fields to execution logs

Revision ID: ba92e300a578
Revises: 957cd111d089
Create Date: 2026-01-15 15:37:19.310337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba92e300a578'
down_revision: Union[str, Sequence[str], None] = '957cd111d089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_logs', sa.Column('attempts', sa.Integer(), nullable=False, server_default=sa.text("0")))
    op.add_column('execution_logs', sa.Column('queued_to_dlq', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('execution_logs', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_logs', 'last_error')
    op.drop_column('execution_logs', 'queued_to_dlq')
    op.drop_column('execution_logs', 'attempts')
    # ### end Alembic commands ###
